// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WUhCNgcV9CtxKlewV_rCYtODm8JquUU',
    appId: '1:589201624295:android:3fa15fb3026b7706f72642',
    messagingSenderId: '589201624295',
    projectId: 'vetconnect-5a6ba',
    databaseURL: 'https://vetconnect-5a6ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vetconnect-5a6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXU6vVYBBnHisWOqOriAGa6L_L0qF6xo',
    appId: '1:589201624295:ios:4e1b2aa264f7f05af72642',
    messagingSenderId: '589201624295',
    projectId: 'vetconnect-5a6ba',
    databaseURL: 'https://vetconnect-5a6ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vetconnect-5a6ba.appspot.com',
    iosBundleId: 'com.example.vetConnect',
  );
}
